#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true

#MPP
kotlin.mpp.enableCInteropCommonization=true
kotlin.apple.deprecated.allowUsingEmbedAndSignWithCocoaPodsDependencies=true
kotlin.native.ignoreDisabledTargets=true
kotlin.native.cacheKind.iosSimulatorArm64=static
kotlin.native.cacheKind.iosArm64=static
kotlin.incremental.native=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#Workshop
workshop.enableIos=false
workshop.iosX64=false
